GET localhost:8080/user/234


###


GET localhost:8080/user

###

POST localhost:8080/user/post
Content-Type: application/json


{
  "firstName": "Torben",
  "lastName": "Steinmoel",
  "email": "torben@gmail.com",
  "id": "123L"
}

###